# coding: utf-8

"""
    E2 Node API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.debugging_api import DebuggingApi  # noqa: E501


class TestDebuggingApi(unittest.TestCase):
    """DebuggingApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DebuggingApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_u_e_get(self) -> None:
        """Test case for u_e_get

        Get the list of UEs connected to the NodeB  # noqa: E501
        """
        pass

    def test_u_eimsi_info_get(self) -> None:
        """Test case for u_eimsi_info_get

        Get the information of the UE associated with the NodeB  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
