# coding: utf-8

"""
    E2 Node UE API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.ue_get200_response_inner import UEGet200ResponseInner  # noqa: E501

class TestUEGet200ResponseInner(unittest.TestCase):
    """UEGet200ResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UEGet200ResponseInner:
        """Test UEGet200ResponseInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UEGet200ResponseInner`
        """
        model = UEGet200ResponseInner()  # noqa: E501
        if include_optional:
            return UEGet200ResponseInner(
                i_msi = ''
            )
        else:
            return UEGet200ResponseInner(
        )
        """

    def testUEGet200ResponseInner(self):
        """Test UEGet200ResponseInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
