# coding: utf-8

"""
    E2 Node UE API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.ueimsi_anr_put_request import UEIMSIAnrPutRequest  # noqa: E501

class TestUEIMSIAnrPutRequest(unittest.TestCase):
    """UEIMSIAnrPutRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UEIMSIAnrPutRequest:
        """Test UEIMSIAnrPutRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UEIMSIAnrPutRequest`
        """
        model = UEIMSIAnrPutRequest()  # noqa: E501
        if include_optional:
            return UEIMSIAnrPutRequest(
                nodeb_list = [
                    openapi_client.models.anr_payload.anr_payload(
                        nodeb = openapi_client.models.nodeb_descriptor.nodeb_descriptor(
                            nodeb_id = '', ), 
                        rsrp = 1.337, 
                        rsrq = 1.337, 
                        sinr = 1.337, 
                        cqi = 1.337, 
                        bler = 1.337, )
                    ]
            )
        else:
            return UEIMSIAnrPutRequest(
        )
        """

    def testUEIMSIAnrPutRequest(self):
        """Test UEIMSIAnrPutRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
