# coding: utf-8

"""
    E2 Node UE API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.data_plane_flow import DataPlaneFlow  # noqa: E501

class TestDataPlaneFlow(unittest.TestCase):
    """DataPlaneFlow unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DataPlaneFlow:
        """Test DataPlaneFlow
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DataPlaneFlow`
        """
        model = DataPlaneFlow()  # noqa: E501
        if include_optional:
            return DataPlaneFlow(
                average_throughput = 1.337,
                latency = 1.337
            )
        else:
            return DataPlaneFlow(
        )
        """

    def testDataPlaneFlow(self):
        """Test DataPlaneFlow"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
