/**
* E2 Node API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "_endpoints_get_200_response_endpoints_inner.h"
#include "Helpers.h"

#include <sstream>

namespace org::openapitools::server::model
{

_endpoints_get_200_response_endpoints_inner::_endpoints_get_200_response_endpoints_inner()
{
    m_Method = "";
    m_MethodIsSet = false;
    m_Uri = "";
    m_UriIsSet = false;
    m_Description = "";
    m_DescriptionIsSet = false;
    
}

void _endpoints_get_200_response_endpoints_inner::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool _endpoints_get_200_response_endpoints_inner::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool _endpoints_get_200_response_endpoints_inner::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "_endpoints_get_200_response_endpoints_inner" : pathPrefix;

                
    return success;
}

bool _endpoints_get_200_response_endpoints_inner::operator==(const _endpoints_get_200_response_endpoints_inner& rhs) const
{
    return
    
    
    
    ((!methodIsSet() && !rhs.methodIsSet()) || (methodIsSet() && rhs.methodIsSet() && getMethod() == rhs.getMethod())) &&
    
    
    ((!uriIsSet() && !rhs.uriIsSet()) || (uriIsSet() && rhs.uriIsSet() && getUri() == rhs.getUri())) &&
    
    
    ((!descriptionIsSet() && !rhs.descriptionIsSet()) || (descriptionIsSet() && rhs.descriptionIsSet() && getDescription() == rhs.getDescription()))
    
    ;
}

bool _endpoints_get_200_response_endpoints_inner::operator!=(const _endpoints_get_200_response_endpoints_inner& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const _endpoints_get_200_response_endpoints_inner& o)
{
    j = nlohmann::json::object();
    if(o.methodIsSet())
        j["method"] = o.m_Method;
    if(o.uriIsSet())
        j["uri"] = o.m_Uri;
    if(o.descriptionIsSet())
        j["description"] = o.m_Description;
    
}

void from_json(const nlohmann::json& j, _endpoints_get_200_response_endpoints_inner& o)
{
    if(j.find("method") != j.end())
    {
        j.at("method").get_to(o.m_Method);
        o.m_MethodIsSet = true;
    } 
    if(j.find("uri") != j.end())
    {
        j.at("uri").get_to(o.m_Uri);
        o.m_UriIsSet = true;
    } 
    if(j.find("description") != j.end())
    {
        j.at("description").get_to(o.m_Description);
        o.m_DescriptionIsSet = true;
    } 
    
}

std::string _endpoints_get_200_response_endpoints_inner::getMethod() const
{
    return m_Method;
}
void _endpoints_get_200_response_endpoints_inner::setMethod(std::string const& value)
{
    m_Method = value;
    m_MethodIsSet = true;
}
bool _endpoints_get_200_response_endpoints_inner::methodIsSet() const
{
    return m_MethodIsSet;
}
void _endpoints_get_200_response_endpoints_inner::unsetMethod()
{
    m_MethodIsSet = false;
}
std::string _endpoints_get_200_response_endpoints_inner::getUri() const
{
    return m_Uri;
}
void _endpoints_get_200_response_endpoints_inner::setUri(std::string const& value)
{
    m_Uri = value;
    m_UriIsSet = true;
}
bool _endpoints_get_200_response_endpoints_inner::uriIsSet() const
{
    return m_UriIsSet;
}
void _endpoints_get_200_response_endpoints_inner::unsetUri()
{
    m_UriIsSet = false;
}
std::string _endpoints_get_200_response_endpoints_inner::getDescription() const
{
    return m_Description;
}
void _endpoints_get_200_response_endpoints_inner::setDescription(std::string const& value)
{
    m_Description = value;
    m_DescriptionIsSet = true;
}
bool _endpoints_get_200_response_endpoints_inner::descriptionIsSet() const
{
    return m_DescriptionIsSet;
}
void _endpoints_get_200_response_endpoints_inner::unsetDescription()
{
    m_DescriptionIsSet = false;
}


} // namespace org::openapitools::server::model

