/**
* E2 Node API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * _endpoints_get_200_response.h
 *
 * 
 */

#ifndef _endpoints_get_200_response_H_
#define _endpoints_get_200_response_H_


#include "_endpoints_get_200_response_endpoints_inner.h"
#include <vector>
#include <nlohmann/json.hpp>

namespace org::openapitools::server::model
{

/// <summary>
/// 
/// </summary>
class  _endpoints_get_200_response
{
public:
    _endpoints_get_200_response();
    virtual ~_endpoints_get_200_response() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const _endpoints_get_200_response& rhs) const;
    bool operator!=(const _endpoints_get_200_response& rhs) const;

    /////////////////////////////////////////////
    /// _endpoints_get_200_response members

    /// <summary>
    /// 
    /// </summary>
    std::vector<org::openapitools::server::model::_endpoints_get_200_response_endpoints_inner> getEndpoints() const;
    void setEndpoints(std::vector<org::openapitools::server::model::_endpoints_get_200_response_endpoints_inner> const& value);
    bool endpointsIsSet() const;
    void unsetEndpoints();

    friend  void to_json(nlohmann::json& j, const _endpoints_get_200_response& o);
    friend  void from_json(const nlohmann::json& j, _endpoints_get_200_response& o);
protected:
    std::vector<org::openapitools::server::model::_endpoints_get_200_response_endpoints_inner> m_Endpoints;
    bool m_EndpointsIsSet;
    
};

} // namespace org::openapitools::server::model

#endif /* _endpoints_get_200_response_H_ */
