/**
* E2 Node API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * _endpoints_get_200_response_endpoints_inner.h
 *
 * 
 */

#ifndef _endpoints_get_200_response_endpoints_inner_H_
#define _endpoints_get_200_response_endpoints_inner_H_


#include <string>
#include <nlohmann/json.hpp>

namespace org::openapitools::server::model
{

/// <summary>
/// 
/// </summary>
class  _endpoints_get_200_response_endpoints_inner
{
public:
    _endpoints_get_200_response_endpoints_inner();
    virtual ~_endpoints_get_200_response_endpoints_inner() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const _endpoints_get_200_response_endpoints_inner& rhs) const;
    bool operator!=(const _endpoints_get_200_response_endpoints_inner& rhs) const;

    /////////////////////////////////////////////
    /// _endpoints_get_200_response_endpoints_inner members

    /// <summary>
    /// 
    /// </summary>
    std::string getMethod() const;
    void setMethod(std::string const& value);
    bool methodIsSet() const;
    void unsetMethod();
    /// <summary>
    /// 
    /// </summary>
    std::string getUri() const;
    void setUri(std::string const& value);
    bool uriIsSet() const;
    void unsetUri();
    /// <summary>
    /// 
    /// </summary>
    std::string getDescription() const;
    void setDescription(std::string const& value);
    bool descriptionIsSet() const;
    void unsetDescription();

    friend  void to_json(nlohmann::json& j, const _endpoints_get_200_response_endpoints_inner& o);
    friend  void from_json(const nlohmann::json& j, _endpoints_get_200_response_endpoints_inner& o);
protected:
    std::string m_Method;
    bool m_MethodIsSet;
    std::string m_Uri;
    bool m_UriIsSet;
    std::string m_Description;
    bool m_DescriptionIsSet;
    
};

} // namespace org::openapitools::server::model

#endif /* _endpoints_get_200_response_endpoints_inner_H_ */
