/**
* E2 Node API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "_UE__iMSI__flow_put_request.h"
#include "Helpers.h"

#include <sstream>

namespace org::openapitools::server::model
{

_UE__iMSI__flow_put_request::_UE__iMSI__flow_put_request()
{
    m_FlowIsSet = false;
    
}

void _UE__iMSI__flow_put_request::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool _UE__iMSI__flow_put_request::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool _UE__iMSI__flow_put_request::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "_UE__iMSI__flow_put_request" : pathPrefix;

        
    return success;
}

bool _UE__iMSI__flow_put_request::operator==(const _UE__iMSI__flow_put_request& rhs) const
{
    return
    
    
    
    ((!flowIsSet() && !rhs.flowIsSet()) || (flowIsSet() && rhs.flowIsSet() && getFlow() == rhs.getFlow()))
    
    ;
}

bool _UE__iMSI__flow_put_request::operator!=(const _UE__iMSI__flow_put_request& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const _UE__iMSI__flow_put_request& o)
{
    j = nlohmann::json::object();
    if(o.flowIsSet())
        j["flow"] = o.m_Flow;
    
}

void from_json(const nlohmann::json& j, _UE__iMSI__flow_put_request& o)
{
    if(j.find("flow") != j.end())
    {
        j.at("flow").get_to(o.m_Flow);
        o.m_FlowIsSet = true;
    } 
    
}

org::openapitools::server::model::Data_plane_flow _UE__iMSI__flow_put_request::getFlow() const
{
    return m_Flow;
}
void _UE__iMSI__flow_put_request::setFlow(org::openapitools::server::model::Data_plane_flow const& value)
{
    m_Flow = value;
    m_FlowIsSet = true;
}
bool _UE__iMSI__flow_put_request::flowIsSet() const
{
    return m_FlowIsSet;
}
void _UE__iMSI__flow_put_request::unsetFlow()
{
    m_FlowIsSet = false;
}


} // namespace org::openapitools::server::model

