/**
* E2 Node API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "_UE__iMSI__info_get_200_response.h"
#include "Helpers.h"

#include <sstream>

namespace org::openapitools::server::model
{

_UE__iMSI__info_get_200_response::_UE__iMSI__info_get_200_response()
{
    m_InfoIsSet = false;
    
}

void _UE__iMSI__info_get_200_response::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool _UE__iMSI__info_get_200_response::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool _UE__iMSI__info_get_200_response::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "_UE__iMSI__info_get_200_response" : pathPrefix;

        
    return success;
}

bool _UE__iMSI__info_get_200_response::operator==(const _UE__iMSI__info_get_200_response& rhs) const
{
    return
    
    
    
    ((!infoIsSet() && !rhs.infoIsSet()) || (infoIsSet() && rhs.infoIsSet() && getInfo() == rhs.getInfo()))
    
    ;
}

bool _UE__iMSI__info_get_200_response::operator!=(const _UE__iMSI__info_get_200_response& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const _UE__iMSI__info_get_200_response& o)
{
    j = nlohmann::json::object();
    if(o.infoIsSet())
        j["info"] = o.m_Info;
    
}

void from_json(const nlohmann::json& j, _UE__iMSI__info_get_200_response& o)
{
    if(j.find("info") != j.end())
    {
        j.at("info").get_to(o.m_Info);
        o.m_InfoIsSet = true;
    } 
    
}

org::openapitools::server::model::Ue_descriptor _UE__iMSI__info_get_200_response::getInfo() const
{
    return m_Info;
}
void _UE__iMSI__info_get_200_response::setInfo(org::openapitools::server::model::Ue_descriptor const& value)
{
    m_Info = value;
    m_InfoIsSet = true;
}
bool _UE__iMSI__info_get_200_response::infoIsSet() const
{
    return m_InfoIsSet;
}
void _UE__iMSI__info_get_200_response::unsetInfo()
{
    m_InfoIsSet = false;
}


} // namespace org::openapitools::server::model

