/**
* E2 Node API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "Data_plane_flow.h"
#include "Helpers.h"

#include <sstream>

namespace org::openapitools::server::model
{

Data_plane_flow::Data_plane_flow()
{
    m_AverageThroughput = 0.0;
    m_Latency = 0.0;
    
}

void Data_plane_flow::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool Data_plane_flow::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool Data_plane_flow::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "Data_plane_flow" : pathPrefix;

            
    return success;
}

bool Data_plane_flow::operator==(const Data_plane_flow& rhs) const
{
    return
    
    
    (getAverageThroughput() == rhs.getAverageThroughput())
     &&
    
    (getLatency() == rhs.getLatency())
    
    
    ;
}

bool Data_plane_flow::operator!=(const Data_plane_flow& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const Data_plane_flow& o)
{
    j = nlohmann::json::object();
    j["averageThroughput"] = o.m_AverageThroughput;
    j["latency"] = o.m_Latency;
    
}

void from_json(const nlohmann::json& j, Data_plane_flow& o)
{
    j.at("averageThroughput").get_to(o.m_AverageThroughput);
    j.at("latency").get_to(o.m_Latency);
    
}

double Data_plane_flow::getAverageThroughput() const
{
    return m_AverageThroughput;
}
void Data_plane_flow::setAverageThroughput(double const value)
{
    m_AverageThroughput = value;
}
double Data_plane_flow::getLatency() const
{
    return m_Latency;
}
void Data_plane_flow::setLatency(double const value)
{
    m_Latency = value;
}


} // namespace org::openapitools::server::model

