/**
* E2 Node API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * Nodeb_descriptor.h
 *
 * 
 */

#ifndef Nodeb_descriptor_H_
#define Nodeb_descriptor_H_


#include <nlohmann/json.hpp>

namespace org::openapitools::server::model
{

/// <summary>
/// 
/// </summary>
class  Nodeb_descriptor
{
public:
    Nodeb_descriptor();
    virtual ~Nodeb_descriptor() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const Nodeb_descriptor& rhs) const;
    bool operator!=(const Nodeb_descriptor& rhs) const;

    /////////////////////////////////////////////
    /// Nodeb_descriptor members

    /// <summary>
    /// 
    /// </summary>
    int32_t getNodebId() const;
    void setNodebId(int32_t const value);

    friend  void to_json(nlohmann::json& j, const Nodeb_descriptor& o);
    friend  void from_json(const nlohmann::json& j, Nodeb_descriptor& o);
protected:
    int32_t m_Nodeb_id;

    
};

} // namespace org::openapitools::server::model

#endif /* Nodeb_descriptor_H_ */
