/**
 * UE Manager API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.1.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/_UE_handover_post_request.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {



_UE_handover_post_request::_UE_handover_post_request()
{
    m_Imsi = utility::conversions::to_string_t("");
    m_ImsiIsSet = false;
    m_GnbId = utility::conversions::to_string_t("");
    m_GnbIdIsSet = false;
}

_UE_handover_post_request::~_UE_handover_post_request()
{
}

void _UE_handover_post_request::validate()
{
    // TODO: implement validation
}

web::json::value _UE_handover_post_request::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_ImsiIsSet)
    {
        val[utility::conversions::to_string_t(U("imsi"))] = ModelBase::toJson(m_Imsi);
    }
    if(m_GnbIdIsSet)
    {
        val[utility::conversions::to_string_t(U("gnbId"))] = ModelBase::toJson(m_GnbId);
    }

    return val;
}

bool _UE_handover_post_request::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("imsi"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("imsi")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setImsi;
            ok &= ModelBase::fromJson(fieldValue, refVal_setImsi);
            setImsi(refVal_setImsi);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("gnbId"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("gnbId")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setGnbId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setGnbId);
            setGnbId(refVal_setGnbId);
        }
    }
    return ok;
}

void _UE_handover_post_request::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_ImsiIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("imsi")), m_Imsi));
    }
    if(m_GnbIdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("gnbId")), m_GnbId));
    }
}

bool _UE_handover_post_request::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("imsi"))))
    {
        utility::string_t refVal_setImsi;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("imsi"))), refVal_setImsi );
        setImsi(refVal_setImsi);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("gnbId"))))
    {
        utility::string_t refVal_setGnbId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("gnbId"))), refVal_setGnbId );
        setGnbId(refVal_setGnbId);
    }
    return ok;
}

utility::string_t _UE_handover_post_request::getImsi() const
{
    return m_Imsi;
}

void _UE_handover_post_request::setImsi(const utility::string_t& value)
{
    m_Imsi = value;
    m_ImsiIsSet = true;
}

bool _UE_handover_post_request::imsiIsSet() const
{
    return m_ImsiIsSet;
}

void _UE_handover_post_request::unsetImsi()
{
    m_ImsiIsSet = false;
}
utility::string_t _UE_handover_post_request::getGnbId() const
{
    return m_GnbId;
}

void _UE_handover_post_request::setGnbId(const utility::string_t& value)
{
    m_GnbId = value;
    m_GnbIdIsSet = true;
}

bool _UE_handover_post_request::gnbIdIsSet() const
{
    return m_GnbIdIsSet;
}

void _UE_handover_post_request::unsetGnbId()
{
    m_GnbIdIsSet = false;
}
}
}
}
}


