# coding: utf-8

"""
    E2 Node UE API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.e2_node_management_api import E2NodeManagementApi  # noqa: E501


class TestE2NodeManagementApi(unittest.TestCase):
    """E2NodeManagementApi unit test stubs"""

    def setUp(self) -> None:
        self.api = E2NodeManagementApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_e2_node_get(self) -> None:
        """Test case for e2_node_get

        Get E2Node informations, for example E2Node ID  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
