# coding: utf-8

"""
    E2 Node UE API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.ue_management_api import UEManagementApi  # noqa: E501


class TestUEManagementApi(unittest.TestCase):
    """UEManagementApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UEManagementApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_u_eimsi_delete(self) -> None:
        """Test case for u_eimsi_delete

        Unregister a mobile UE  # noqa: E501
        """
        pass

    def test_u_eimsi_put(self) -> None:
        """Test case for u_eimsi_put

        Create or update information for a mobile UE  # noqa: E501
        """
        pass

    def test_u_es_get(self) -> None:
        """Test case for u_es_get

        List all active UE's IMSIs  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
