# coding: utf-8

"""
    E2 Node UE API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.ues_get200_response import UEsGet200Response  # noqa: E501

class TestUEsGet200Response(unittest.TestCase):
    """UEsGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UEsGet200Response:
        """Test UEsGet200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UEsGet200Response`
        """
        model = UEsGet200Response()  # noqa: E501
        if include_optional:
            return UEsGet200Response(
                imsis_active = [
                    ''
                    ],
                message = ''
            )
        else:
            return UEsGet200Response(
        )
        """

    def testUEsGet200Response(self):
        """Test UEsGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
