# coding: utf-8

"""
    E2 Node UE API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.e2_node_get200_response import E2NodeGet200Response  # noqa: E501

class TestE2NodeGet200Response(unittest.TestCase):
    """E2NodeGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> E2NodeGet200Response:
        """Test E2NodeGet200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `E2NodeGet200Response`
        """
        model = E2NodeGet200Response()  # noqa: E501
        if include_optional:
            return E2NodeGet200Response(
                g_nbid = ''
            )
        else:
            return E2NodeGet200Response(
        )
        """

    def testE2NodeGet200Response(self):
        """Test E2NodeGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
