# coding: utf-8

"""
    E2 Node UE API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.ueimsi_put_request_available_gnbs_inner import UEIMSIPutRequestAvailableGNBsInner  # noqa: E501

class TestUEIMSIPutRequestAvailableGNBsInner(unittest.TestCase):
    """UEIMSIPutRequestAvailableGNBsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UEIMSIPutRequestAvailableGNBsInner:
        """Test UEIMSIPutRequestAvailableGNBsInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UEIMSIPutRequestAvailableGNBsInner`
        """
        model = UEIMSIPutRequestAvailableGNBsInner()  # noqa: E501
        if include_optional:
            return UEIMSIPutRequestAvailableGNBsInner(
                g_nb_id = '',
                g_nb_rsrp = 56,
                g_nb_rssi = 56,
                g_nb_rsrq = 56,
                connected = True
            )
        else:
            return UEIMSIPutRequestAvailableGNBsInner(
                g_nb_id = '',
                g_nb_rsrp = 56,
        )
        """

    def testUEIMSIPutRequestAvailableGNBsInner(self):
        """Test UEIMSIPutRequestAvailableGNBsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
