# coding: utf-8

"""
    E2 Node UE API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.testing_api import TestingApi  # noqa: E501


class TestTestingApi(unittest.TestCase):
    """TestingApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TestingApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_test_get(self) -> None:
        """Test case for test_get

        Test API connectivity  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
