from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class UEDisconnectDeleteRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, imsi=None):  # noqa: E501
        """UEDisconnectDeleteRequest - a model defined in OpenAPI

        :param imsi: The imsi of this UEDisconnectDeleteRequest.  # noqa: E501
        :type imsi: str
        """
        self.openapi_types = {
            'imsi': str
        }

        self.attribute_map = {
            'imsi': 'imsi'
        }

        self._imsi = imsi

    @classmethod
    def from_dict(cls, dikt) -> 'UEDisconnectDeleteRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _UE_disconnect_delete_request of this UEDisconnectDeleteRequest.  # noqa: E501
        :rtype: UEDisconnectDeleteRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def imsi(self) -> str:
        """Gets the imsi of this UEDisconnectDeleteRequest.

        The International Mobile Subscriber Identity of the UE to disconnect  # noqa: E501

        :return: The imsi of this UEDisconnectDeleteRequest.
        :rtype: str
        """
        return self._imsi

    @imsi.setter
    def imsi(self, imsi: str):
        """Sets the imsi of this UEDisconnectDeleteRequest.

        The International Mobile Subscriber Identity of the UE to disconnect  # noqa: E501

        :param imsi: The imsi of this UEDisconnectDeleteRequest.
        :type imsi: str
        """

        self._imsi = imsi
