from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class UEHandoverPostRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, imsi=None, gnb_id=None):  # noqa: E501
        """UEHandoverPostRequest - a model defined in OpenAPI

        :param imsi: The imsi of this UEHandoverPostRequest.  # noqa: E501
        :type imsi: str
        :param gnb_id: The gnb_id of this UEHandoverPostRequest.  # noqa: E501
        :type gnb_id: str
        """
        self.openapi_types = {
            'imsi': str,
            'gnb_id': str
        }

        self.attribute_map = {
            'imsi': 'imsi',
            'gnb_id': 'gnbId'
        }

        self._imsi = imsi
        self._gnb_id = gnb_id

    @classmethod
    def from_dict(cls, dikt) -> 'UEHandoverPostRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _UE_handover_post_request of this UEHandoverPostRequest.  # noqa: E501
        :rtype: UEHandoverPostRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def imsi(self) -> str:
        """Gets the imsi of this UEHandoverPostRequest.

        The International Mobile Subscriber Identity of the UE  # noqa: E501

        :return: The imsi of this UEHandoverPostRequest.
        :rtype: str
        """
        return self._imsi

    @imsi.setter
    def imsi(self, imsi: str):
        """Sets the imsi of this UEHandoverPostRequest.

        The International Mobile Subscriber Identity of the UE  # noqa: E501

        :param imsi: The imsi of this UEHandoverPostRequest.
        :type imsi: str
        """

        self._imsi = imsi

    @property
    def gnb_id(self) -> str:
        """Gets the gnb_id of this UEHandoverPostRequest.

        The gNB ID to which the UE is being handed over  # noqa: E501

        :return: The gnb_id of this UEHandoverPostRequest.
        :rtype: str
        """
        return self._gnb_id

    @gnb_id.setter
    def gnb_id(self, gnb_id: str):
        """Sets the gnb_id of this UEHandoverPostRequest.

        The gNB ID to which the UE is being handed over  # noqa: E501

        :param gnb_id: The gnb_id of this UEHandoverPostRequest.
        :type gnb_id: str
        """

        self._gnb_id = gnb_id
