# coding: utf-8

"""
    E2 Node UE API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.nodeb_descriptor import NodebDescriptor  # noqa: E501

class TestNodebDescriptor(unittest.TestCase):
    """NodebDescriptor unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NodebDescriptor:
        """Test NodebDescriptor
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NodebDescriptor`
        """
        model = NodebDescriptor()  # noqa: E501
        if include_optional:
            return NodebDescriptor(
                nodeb_id = ''
            )
        else:
            return NodebDescriptor(
                nodeb_id = '',
        )
        """

    def testNodebDescriptor(self):
        """Test NodebDescriptor"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
