# coding: utf-8

"""
    E2 Node UE API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.ueimsi_flow_put_request import UEIMSIFlowPutRequest  # noqa: E501

class TestUEIMSIFlowPutRequest(unittest.TestCase):
    """UEIMSIFlowPutRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UEIMSIFlowPutRequest:
        """Test UEIMSIFlowPutRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UEIMSIFlowPutRequest`
        """
        model = UEIMSIFlowPutRequest()  # noqa: E501
        if include_optional:
            return UEIMSIFlowPutRequest(
                flow = openapi_client.models.data_plane_flow.data_plane_flow(
                    average_throughput = 1.337, 
                    latency = 1.337, )
            )
        else:
            return UEIMSIFlowPutRequest(
        )
        """

    def testUEIMSIFlowPutRequest(self):
        """Test UEIMSIFlowPutRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
