# coding: utf-8

"""
    E2 Node UE API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.management_api import ManagementApi  # noqa: E501


class TestManagementApi(unittest.TestCase):
    """ManagementApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ManagementApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_u_eimsi_admission_delete(self) -> None:
        """Test case for u_eimsi_admission_delete

        Disconnects a UE from a nodeb  # noqa: E501
        """
        pass

    def test_u_eimsi_admission_put(self) -> None:
        """Test case for u_eimsi_admission_put

        Connects a UE to a nodeb  # noqa: E501
        """
        pass

    def test_u_eimsi_anr_put(self) -> None:
        """Test case for u_eimsi_anr_put

        Update ANR data  # noqa: E501
        """
        pass

    def test_u_eimsi_flow_put(self) -> None:
        """Test case for u_eimsi_flow_put

        update Data Plane Information  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
