# coding: utf-8

"""
    E2 Node API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.endpoints_get200_response import EndpointsGet200Response  # noqa: E501

class TestEndpointsGet200Response(unittest.TestCase):
    """EndpointsGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EndpointsGet200Response:
        """Test EndpointsGet200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EndpointsGet200Response`
        """
        model = EndpointsGet200Response()  # noqa: E501
        if include_optional:
            return EndpointsGet200Response(
                endpoints = [
                    ''
                    ]
            )
        else:
            return EndpointsGet200Response(
        )
        """

    def testEndpointsGet200Response(self):
        """Test EndpointsGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
