/**
 * UE Manager API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.1.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * _UE_handover_post_request.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL__UE_handover_post_request_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL__UE_handover_post_request_H_


#include "CppRestOpenAPIClient/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {


/// <summary>
/// 
/// </summary>
class  _UE_handover_post_request
    : public ModelBase
{
public:
    _UE_handover_post_request();
    virtual ~_UE_handover_post_request();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// _UE_handover_post_request members

    /// <summary>
    /// The International Mobile Subscriber Identity of the UE
    /// </summary>
    utility::string_t getImsi() const;
    bool imsiIsSet() const;
    void unsetImsi();

    void setImsi(const utility::string_t& value);

    /// <summary>
    /// The gNB ID to which the UE is being handed over
    /// </summary>
    utility::string_t getGnbId() const;
    bool gnbIdIsSet() const;
    void unsetGnbId();

    void setGnbId(const utility::string_t& value);


protected:
    utility::string_t m_Imsi;
    bool m_ImsiIsSet;
    utility::string_t m_GnbId;
    bool m_GnbIdIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL__UE_handover_post_request_H_ */
