/**
* E2 Node API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * DebuggingApi.h
 *
 * 
 */

#ifndef DebuggingApi_H_
#define DebuggingApi_H_


#include "ApiBase.h"

#include <pistache/http.h>
#include <pistache/router.h>
#include <pistache/http_headers.h>

#include <optional>
#include <utility>

#include "_UE__iMSI__info_get_200_response.h"
#include "_UE_get_200_response.h"
#include <string>

namespace org::openapitools::server::api
{

class  DebuggingApi : public ApiBase {
public:
    explicit DebuggingApi(const std::shared_ptr<Pistache::Rest::Router>& rtr);
    ~DebuggingApi() override = default;
    void init() override;

    static const std::string base;

private:
    void setupRoutes();

    void u_e_get_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);
    void u_eimsi_info_get_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);
    void debugging_api_default_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);

    /// <summary>
    /// Helper function to handle unexpected Exceptions during Parameter parsing and validation.
    /// May be overridden to return custom error formats. This is called inside a catch block.
    /// Important: When overriding, do not call `throw ex;`, but instead use `throw;`.
    /// </summary>
    virtual std::pair<Pistache::Http::Code, std::string> handleParsingException(const std::exception& ex) const noexcept;

    /// <summary>
    /// Helper function to handle unexpected Exceptions during processing of the request in handler functions.
    /// May be overridden to return custom error formats. This is called inside a catch block.
    /// Important: When overriding, do not call `throw ex;`, but instead use `throw;`.
    /// </summary>
    virtual std::pair<Pistache::Http::Code, std::string> handleOperationException(const std::exception& ex) const noexcept;

    /// <summary>
    /// Get the list of UEs connected to the NodeB
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    virtual void u_e_get(Pistache::Http::ResponseWriter &response) = 0;
    /// <summary>
    /// Get the information of the UE associated with the NodeB
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="iMSI"></param>
    virtual void u_eimsi_info_get(const std::string &iMSI, Pistache::Http::ResponseWriter &response) = 0;

};

} // namespace org::openapitools::server::api

#endif /* DebuggingApi_H_ */

