# coding: utf-8

"""
    E2 Node API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, Field, StrictStr
from typing import Any, ClassVar, Dict, List
from openapi_client.models.anr_payload import AnrPayload
from openapi_client.models.data_plane_flow import DataPlaneFlow
from typing import Optional, Set
from typing_extensions import Self

class UeDescriptor(BaseModel):
    """
    UeDescriptor
    """ # noqa: E501
    data_plane_flow: DataPlaneFlow
    anr_payload: List[AnrPayload]
    endpoint: StrictStr = Field(description="Endpoint url to send operation to an UE")
    __properties: ClassVar[List[str]] = ["data_plane_flow", "anr_payload", "endpoint"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UeDescriptor from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of data_plane_flow
        if self.data_plane_flow:
            _dict['data_plane_flow'] = self.data_plane_flow.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in anr_payload (list)
        _items = []
        if self.anr_payload:
            for _item in self.anr_payload:
                if _item:
                    _items.append(_item.to_dict())
            _dict['anr_payload'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UeDescriptor from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "data_plane_flow": DataPlaneFlow.from_dict(obj["data_plane_flow"]) if obj.get("data_plane_flow") is not None else None,
            "anr_payload": [AnrPayload.from_dict(_item) for _item in obj["anr_payload"]] if obj.get("anr_payload") is not None else None,
            "endpoint": obj.get("endpoint")
        })
        return _obj


