/**
 * UE Manager API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.1.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * TestingApi.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_API_TestingApi_H_
#define ORG_OPENAPITOOLS_CLIENT_API_TestingApi_H_



#include "CppRestOpenAPIClient/ApiClient.h"
#include "CppRestOpenAPIClient/ModelBase.h"
#include <boost/optional.hpp>

namespace org {
namespace openapitools {
namespace client {
namespace api {

using namespace org::openapitools::client::model;



class  TestingApi 
{
public:

    explicit TestingApi( std::shared_ptr<const ApiClient> apiClient );

    virtual ~TestingApi();

    /// <summary>
    /// Test API connectivity
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    pplx::task<void> testGet(
    ) const;

protected:
    std::shared_ptr<const ApiClient> m_ApiClient;
};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_API_TestingApi_H_ */

