/**
 * UE Manager API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.1.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * UEManagementApi.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_API_UEManagementApi_H_
#define ORG_OPENAPITOOLS_CLIENT_API_UEManagementApi_H_



#include "CppRestOpenAPIClient/ApiClient.h"

#include "CppRestOpenAPIClient/model/_UE_disconnect_delete_request.h"
#include "CppRestOpenAPIClient/model/_UE_handover_post_request.h"
#include <boost/optional.hpp>

namespace org {
namespace openapitools {
namespace client {
namespace api {

using namespace org::openapitools::client::model;



class  UEManagementApi 
{
public:

    explicit UEManagementApi( std::shared_ptr<const ApiClient> apiClient );

    virtual ~UEManagementApi();

    /// <summary>
    /// Disconnect UE
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="uEDisconnectDeleteRequest"></param>
    pplx::task<void> uEDisconnectDelete(
        std::shared_ptr<_UE_disconnect_delete_request> uEDisconnectDeleteRequest
    ) const;
    /// <summary>
    /// Initiate UE handover
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="uEHandoverPostRequest"></param>
    pplx::task<void> uEHandoverPost(
        std::shared_ptr<_UE_handover_post_request> uEHandoverPostRequest
    ) const;

protected:
    std::shared_ptr<const ApiClient> m_ApiClient;
};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_API_UEManagementApi_H_ */

