/**
* E2 Node API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * ManagementApi.h
 *
 * 
 */

#ifndef ManagementApi_H_
#define ManagementApi_H_


#include "ApiBase.h"

#include <pistache/http.h>
#include <pistache/router.h>
#include <pistache/http_headers.h>

#include <optional>
#include <utility>

#include "_UE__iMSI__admission_put_request.h"
#include "_UE__iMSI__anr_put_request.h"
#include "_UE__iMSI__flow_put_request.h"
#include <string>

namespace org::openapitools::server::api
{

class  ManagementApi : public ApiBase {
public:
    explicit ManagementApi(const std::shared_ptr<Pistache::Rest::Router>& rtr);
    ~ManagementApi() override = default;
    void init() override;

    static const std::string base;

private:
    void setupRoutes();

    void u_eimsi_admission_delete_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);
    void u_eimsi_admission_put_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);
    void u_eimsi_anr_put_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);
    void u_eimsi_flow_put_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);
    void management_api_default_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);

    /// <summary>
    /// Helper function to handle unexpected Exceptions during Parameter parsing and validation.
    /// May be overridden to return custom error formats. This is called inside a catch block.
    /// Important: When overriding, do not call `throw ex;`, but instead use `throw;`.
    /// </summary>
    virtual std::pair<Pistache::Http::Code, std::string> handleParsingException(const std::exception& ex) const noexcept;

    /// <summary>
    /// Helper function to handle unexpected Exceptions during processing of the request in handler functions.
    /// May be overridden to return custom error formats. This is called inside a catch block.
    /// Important: When overriding, do not call `throw ex;`, but instead use `throw;`.
    /// </summary>
    virtual std::pair<Pistache::Http::Code, std::string> handleOperationException(const std::exception& ex) const noexcept;

    /// <summary>
    /// Disconnects a UE from a nodeb
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="iMSI"></param>
    virtual void u_eimsi_admission_delete(const std::string &iMSI, Pistache::Http::ResponseWriter &response) = 0;
    /// <summary>
    /// Connects a UE to a nodeb
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="iMSI"></param>
    /// <param name="uEIMSIAdmissionPutRequest"></param>
    virtual void u_eimsi_admission_put(const std::string &iMSI, const org::openapitools::server::model::_UE__iMSI__admission_put_request &uEIMSIAdmissionPutRequest, Pistache::Http::ResponseWriter &response) = 0;
    /// <summary>
    /// Update ANR data
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="iMSI"></param>
    /// <param name="uEIMSIAnrPutRequest"></param>
    virtual void u_eimsi_anr_put(const std::string &iMSI, const org::openapitools::server::model::_UE__iMSI__anr_put_request &uEIMSIAnrPutRequest, Pistache::Http::ResponseWriter &response) = 0;
    /// <summary>
    /// update Data Plane Information
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="iMSI"></param>
    /// <param name="uEIMSIFlowPutRequest"></param>
    virtual void u_eimsi_flow_put(const std::string &iMSI, const org::openapitools::server::model::_UE__iMSI__flow_put_request &uEIMSIFlowPutRequest, Pistache::Http::ResponseWriter &response) = 0;

};

} // namespace org::openapitools::server::api

#endif /* ManagementApi_H_ */

