/**
* E2 Node UE API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "_UE_get_200_response_inner.h"
#include "Helpers.h"

#include <sstream>

namespace org::openapitools::server::model
{

_UE_get_200_response_inner::_UE_get_200_response_inner()
{
    m_IMSI = "";
    m_IMSIIsSet = false;
    
}

void _UE_get_200_response_inner::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool _UE_get_200_response_inner::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool _UE_get_200_response_inner::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "_UE_get_200_response_inner" : pathPrefix;

        
    return success;
}

bool _UE_get_200_response_inner::operator==(const _UE_get_200_response_inner& rhs) const
{
    return
    
    
    
    ((!iMSIIsSet() && !rhs.iMSIIsSet()) || (iMSIIsSet() && rhs.iMSIIsSet() && getIMSI() == rhs.getIMSI()))
    
    ;
}

bool _UE_get_200_response_inner::operator!=(const _UE_get_200_response_inner& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const _UE_get_200_response_inner& o)
{
    j = nlohmann::json::object();
    if(o.iMSIIsSet())
        j["iMSI"] = o.m_IMSI;
    
}

void from_json(const nlohmann::json& j, _UE_get_200_response_inner& o)
{
    if(j.find("iMSI") != j.end())
    {
        j.at("iMSI").get_to(o.m_IMSI);
        o.m_IMSIIsSet = true;
    } 
    
}

std::string _UE_get_200_response_inner::getIMSI() const
{
    return m_IMSI;
}
void _UE_get_200_response_inner::setIMSI(std::string const& value)
{
    m_IMSI = value;
    m_IMSIIsSet = true;
}
bool _UE_get_200_response_inner::iMSIIsSet() const
{
    return m_IMSIIsSet;
}
void _UE_get_200_response_inner::unsetIMSI()
{
    m_IMSIIsSet = false;
}


} // namespace org::openapitools::server::model

