/**
* E2 Node API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "Anr_payload.h"
#include "Helpers.h"

#include <sstream>

namespace org::openapitools::server::model
{

Anr_payload::Anr_payload()
{
    m_RSRP = 0.0;
    m_RSRQ = 0.0;
    m_SINR = 0.0;
    m_CQI = 0.0;
    m_BLER = 0.0;
    
}

void Anr_payload::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool Anr_payload::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool Anr_payload::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "Anr_payload" : pathPrefix;

        
    try {
        m_Nodeb.validate();
    } catch(org::openapitools::server::helpers::ValidationException) {
        msg << _pathPrefix << ": Nodeb is invalid;";
        success = false;
    }                    
    return success;
}

bool Anr_payload::operator==(const Anr_payload& rhs) const
{
    return
    
    
    (getNodeb() == rhs.getNodeb())
     &&
    
    (getRSRP() == rhs.getRSRP())
     &&
    
    (getRSRQ() == rhs.getRSRQ())
     &&
    
    (getSINR() == rhs.getSINR())
     &&
    
    (getCQI() == rhs.getCQI())
     &&
    
    (getBLER() == rhs.getBLER())
    
    
    ;
}

bool Anr_payload::operator!=(const Anr_payload& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const Anr_payload& o)
{
    j = nlohmann::json::object();
    j["nodeb"] = o.m_Nodeb;
    j["RSRP"] = o.m_RSRP;
    j["RSRQ"] = o.m_RSRQ;
    j["SINR"] = o.m_SINR;
    j["CQI"] = o.m_CQI;
    j["BLER"] = o.m_BLER;
    
}

void from_json(const nlohmann::json& j, Anr_payload& o)
{
    j.at("nodeb").get_to(o.m_Nodeb);
    j.at("RSRP").get_to(o.m_RSRP);
    j.at("RSRQ").get_to(o.m_RSRQ);
    j.at("SINR").get_to(o.m_SINR);
    j.at("CQI").get_to(o.m_CQI);
    j.at("BLER").get_to(o.m_BLER);
    
}

org::openapitools::server::model::Nodeb_descriptor Anr_payload::getNodeb() const
{
    return m_Nodeb;
}
void Anr_payload::setNodeb(org::openapitools::server::model::Nodeb_descriptor const& value)
{
    m_Nodeb = value;
}
double Anr_payload::getRSRP() const
{
    return m_RSRP;
}
void Anr_payload::setRSRP(double const value)
{
    m_RSRP = value;
}
double Anr_payload::getRSRQ() const
{
    return m_RSRQ;
}
void Anr_payload::setRSRQ(double const value)
{
    m_RSRQ = value;
}
double Anr_payload::getSINR() const
{
    return m_SINR;
}
void Anr_payload::setSINR(double const value)
{
    m_SINR = value;
}
double Anr_payload::getCQI() const
{
    return m_CQI;
}
void Anr_payload::setCQI(double const value)
{
    m_CQI = value;
}
double Anr_payload::getBLER() const
{
    return m_BLER;
}
void Anr_payload::setBLER(double const value)
{
    m_BLER = value;
}


} // namespace org::openapitools::server::model

