/**
* E2 Node UE API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "Ue_descriptor.h"
#include "Helpers.h"

#include <sstream>

namespace org::openapitools::server::model
{

Ue_descriptor::Ue_descriptor()
{
    m_Data_plane_flowIsSet = false;
    m_Anr_payloadIsSet = false;
    
}

void Ue_descriptor::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool Ue_descriptor::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool Ue_descriptor::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "Ue_descriptor" : pathPrefix;

             
    if (anrPayloadIsSet())
    {
        const std::vector<org::openapitools::server::model::Anr_payload>& value = m_Anr_payload;
        const std::string currentValuePath = _pathPrefix + ".anrPayload";
                
        
        { // Recursive validation of array elements
            const std::string oldValuePath = currentValuePath;
            int i = 0;
            for (const org::openapitools::server::model::Anr_payload& value : value)
            { 
                const std::string currentValuePath = oldValuePath + "[" + std::to_string(i) + "]";
                        
        success = value.validate(msg, currentValuePath + ".anrPayload") && success;
 
                i++;
            }
        }

    }
    
    return success;
}

bool Ue_descriptor::operator==(const Ue_descriptor& rhs) const
{
    return
    
    
    
    ((!dataPlaneFlowIsSet() && !rhs.dataPlaneFlowIsSet()) || (dataPlaneFlowIsSet() && rhs.dataPlaneFlowIsSet() && getDataPlaneFlow() == rhs.getDataPlaneFlow())) &&
    
    
    ((!anrPayloadIsSet() && !rhs.anrPayloadIsSet()) || (anrPayloadIsSet() && rhs.anrPayloadIsSet() && getAnrPayload() == rhs.getAnrPayload()))
    
    ;
}

bool Ue_descriptor::operator!=(const Ue_descriptor& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const Ue_descriptor& o)
{
    j = nlohmann::json::object();
    if(o.dataPlaneFlowIsSet())
        j["data_plane_flow"] = o.m_Data_plane_flow;
    if(o.anrPayloadIsSet() || !o.m_Anr_payload.empty())
        j["anr_payload"] = o.m_Anr_payload;
    
}

void from_json(const nlohmann::json& j, Ue_descriptor& o)
{
    if(j.find("data_plane_flow") != j.end())
    {
        j.at("data_plane_flow").get_to(o.m_Data_plane_flow);
        o.m_Data_plane_flowIsSet = true;
    } 
    if(j.find("anr_payload") != j.end())
    {
        j.at("anr_payload").get_to(o.m_Anr_payload);
        o.m_Anr_payloadIsSet = true;
    } 
    
}

org::openapitools::server::model::Data_plane_flow Ue_descriptor::getDataPlaneFlow() const
{
    return m_Data_plane_flow;
}
void Ue_descriptor::setDataPlaneFlow(org::openapitools::server::model::Data_plane_flow const& value)
{
    m_Data_plane_flow = value;
    m_Data_plane_flowIsSet = true;
}
bool Ue_descriptor::dataPlaneFlowIsSet() const
{
    return m_Data_plane_flowIsSet;
}
void Ue_descriptor::unsetData_plane_flow()
{
    m_Data_plane_flowIsSet = false;
}
std::vector<org::openapitools::server::model::Anr_payload> Ue_descriptor::getAnrPayload() const
{
    return m_Anr_payload;
}
void Ue_descriptor::setAnrPayload(std::vector<org::openapitools::server::model::Anr_payload> const& value)
{
    m_Anr_payload = value;
    m_Anr_payloadIsSet = true;
}
bool Ue_descriptor::anrPayloadIsSet() const
{
    return m_Anr_payloadIsSet;
}
void Ue_descriptor::unsetAnr_payload()
{
    m_Anr_payloadIsSet = false;
}


} // namespace org::openapitools::server::model

