/**
* E2 Node API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * Ue_descriptor.h
 *
 * 
 */

#ifndef Ue_descriptor_H_
#define Ue_descriptor_H_


#include <string>
#include "Data_plane_flow.h"
#include "Anr_payload.h"
#include <vector>
#include <nlohmann/json.hpp>

namespace org::openapitools::server::model
{

/// <summary>
/// 
/// </summary>
class  Ue_descriptor
{
public:
    Ue_descriptor();
    virtual ~Ue_descriptor() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const Ue_descriptor& rhs) const;
    bool operator!=(const Ue_descriptor& rhs) const;

    /////////////////////////////////////////////
    /// Ue_descriptor members

    /// <summary>
    /// 
    /// </summary>
    org::openapitools::server::model::Data_plane_flow getDataPlaneFlow() const;
    void setDataPlaneFlow(org::openapitools::server::model::Data_plane_flow const& value);
    /// <summary>
    /// 
    /// </summary>
    std::vector<org::openapitools::server::model::Anr_payload> getAnrPayload() const;
    void setAnrPayload(std::vector<org::openapitools::server::model::Anr_payload> const& value);
    /// <summary>
    /// Endpoint url to send operation to an UE
    /// </summary>
    std::string getEndpoint() const;
    void setEndpoint(std::string const& value);

    friend  void to_json(nlohmann::json& j, const Ue_descriptor& o);
    friend  void from_json(const nlohmann::json& j, Ue_descriptor& o);
protected:
    org::openapitools::server::model::Data_plane_flow m_Data_plane_flow;

    std::vector<org::openapitools::server::model::Anr_payload> m_Anr_payload;

    std::string m_Endpoint;

    
};

} // namespace org::openapitools::server::model

#endif /* Ue_descriptor_H_ */
