/**
 * UE Control API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.4.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Cell_descriptor.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_Cell_descriptor_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_Cell_descriptor_H_


#include "ue_client/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {


/// <summary>
/// 
/// </summary>
class  Cell_descriptor
    : public ModelBase
{
public:
    Cell_descriptor();
    virtual ~Cell_descriptor();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// Cell_descriptor members

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getMnc() const;
    bool mncIsSet() const;
    void unsetMnc();

    void setMnc(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getMcc() const;
    bool mccIsSet() const;
    void unsetMcc();

    void setMcc(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    int32_t getNodebId() const;
    bool nodebIdIsSet() const;
    void unsetNodeb_id();

    void setNodebId(int32_t value);


protected:
    utility::string_t m_Mnc;
    bool m_MncIsSet;
    utility::string_t m_Mcc;
    bool m_MccIsSet;
    int32_t m_Nodeb_id;
    bool m_Nodeb_idIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_Cell_descriptor_H_ */
